openapi: 3.0.3
info:
  title: Argent Bank
  description: |
    Remede Agency, une agence spécialisée dans le développement d'applications web.
    Un nouveau projet qui concerne une nouvelle banque qui démarre, Argent Bank, qui essaie de percer dans le secteur et qui a besoin d'aide pour mettre en place son application.

    Phase 2 : Transactions nous sommes encore en phase de conception. De notre côté, nous mettons au point une fonctionnalité pour les transactions qui doit pouvoir permettre aux utilisateurs:
    
    - La méthode HTTP (ex. : GET, POST etc.)
    - La route (ex. : /store/inventory)
    - La description de ce à quoi correspond l’endpoint (ex. : Retour de l'inventaire des animaux de compagnie)
    - Les paramètres possibles pour tenir compte des différents scénarios (ex. : itemId (facultatif) = ID de l'article spécifique à demander à la base de données d'inventaire).
    - Les différentes réponses avec les codes de réponse correspondants qui ont un sens pour cet endpoint (ex. : 404 : réponse d'erreur d'article inconnu).
    
  contact:
    email: noelantoine974@outlook.fr
  license:
    name: Licence Noel Emmanuel
  version: 1.0.11
servers:
  - url: https://localhost:3001/api/v1
security:
  - userAuth: []

components:
  securitySchemes:
    userAuth:
      type: apiKey
      in: header
      name: Authorization
paths:
  /transactions:
    get:
      security:
        - userAuth: []
      tags:
        - transactions
      summary: Récupérer les transactions du mois en cours
      description: |
        Récupère toutes les transactions pour le mois en cours, groupées par compte.
      operationId: getTransactions
      parameters:
        - name: month
          in: query
          description: Mois pour lequel récupérer les transactions (format YYYY-MM)
          required: false
          schema:
            type: string
            pattern: '^\d{4}-(0[1-9]|1[0-2])$'
      responses:
        '200':
          description: Transactions récupérées avec succès
        '400':
          description: Mauvaise requête, le format du mois est incorrect
        '404':
          description: Aucune transaction trouvée pour le mois en cours

  /transactions/{transactionId}:
    get:
      security:
        - userAuth: []
      tags:
        - transactions
      summary: Récupérer les détails d'une transaction
      description: |
        Récupère les détails d'une transaction spécifique.
      operationId: getTransactionDetails
      parameters:
        - name: transactionId
          in: path
          description: ID de la transaction à récupérer
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
        '404':
          description: La transaction spécifiée n'a pas été trouvée

    put:
      security:
        - userAuth: []
      tags:
        - transactions
      summary: Mettre à jour les détails d'une transaction
      description: |
        Met à jour les détails d'une transaction spécifique.
      operationId: updateTransactionDetails
      parameters:
        - name: transactionId
          in: path
          description: ID de la transaction à mettre à jour
          required: true
          schema:
            type: string
      requestBody:
        description: Nouveaux détails de la transaction
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionInput'
      responses:
        '200':
          description: Détails de la transaction mis à jour avec succès
        '400':
          description: Mauvaise requête, le format des données est incorrect
        '404':
          description: La transaction spécifiée n'a pas été trouvée

    delete:
      security:
        - userAuth: []
      tags:
        - transactions
      summary: Supprimer une transaction
      description: |
        Supprime une transaction spécifique.
      operationId: deleteTransaction
      parameters:
        - name: transactionId
          in: path
          description: ID de la transaction à supprimer
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Transaction supprimée avec succès
        '404':
          description: La transaction spécifiée n'a pas été trouvée

components:
  schemas:
    TransactionInput:
      type: object
      properties:
        amount:
          type: number
          description: Montant de la transaction
        date:
          type: string
          format: date
          description: Date de la transaction (format YYYY-MM-DD)
        description:
          type: string
          description: Description de la transaction
        accountId:
          type: string
          description: ID du compte associé à la transaction
      
  
