openapi: 3.0.3
info:
  title: Argent Bank
  description: |
    Remede Agency, une agence spécialisée dans le développement d'applications web.
    Un nouveau projet qui concerne une nouvelle banque qui démarre, Argent Bank, qui essaie de percer dans le secteur et qui a besoin d'aide pour mettre en place son application.

    Phase 2 : Transactions nous sommes encore en phase de conception. De notre côté, nous mettons au point une fonctionnalité pour les transactions qui doit pouvoir permettre aux utilisateurs :

    - La méthode HTTP (ex. : GET, POST, PUT, DELETE.)
  contact:
    email: noelantoine974@outlook.fr
  license:
    name: Licence Noel Emmanuel
  version: 1.0.11
servers:
  - url: https://localhost:3001/api/v1

paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      requestBody:
        description: Login Payload
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: Login Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      requestBody:
        description: Signup Payload
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Signup Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          schema:
            type: string
      requestBody:
        description: Update user profile attributes
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfile'
      responses:
        '200':
          description: User profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts
      summary: Récupérer les comptes utilisateurs
      description: Récupère tous les comptes d'un utilisateur connecté.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Comptes récupérés avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '400':
          description: Requête incorrecte
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Comptes non trouvés
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /user/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Récupérer les transactions par compte
      description: Récupère toutes les transactions pour un compte spécifique.
      parameters:
        - in: path
          name: accountId
          schema:
            type: string
          description: ID du compte
          required: true
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Transactions récupérées avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionSummary'
        '400':
          description: Requête incorrecte
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Compte non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /user/{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Récupérer les détails d'une transaction
      description: Récupère les détails d'une transaction spécifique.
      parameters:
        - in: path
          name: accountId
          schema:
            type: string
          description: ID du compte
          required: true
        - in: path
          name: transactionId
          schema:
            type: string
          description: ID de la transaction
          required: true
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionSummaryDetail'
        '400':
          description: Requête incorrecte
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Transaction non trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Créer une nouvelle transaction
      description: Crée une nouvelle transaction pour un compte spécifique.
      parameters:
        - in: path
          name: accountId
          schema:
            type: string
          description: ID du compte
          required: true
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          schema:
            type: string
      requestBody:
        description: Les détails de la nouvelle transaction
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionSummaryDetail'
      responses:
        '201':
          description: Transaction créée avec succès
        '400':
          description: Données de la transaction invalides
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erreur interne du serveur

    put:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Modifier une transaction
      description: Modifier une transaction existante.
      parameters:
        - in: path
          name: accountId
          schema:
            type: string
          description: ID du compte
          required: true
        - in: path
          name: transactionId
          schema:
            type: string
          description: ID de la transaction
          required: true
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          schema:
            type: string
      requestBody:
        description: Les détails de la transaction à modifier
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionDetail'
      responses:
        '200':
          description: Transaction modifiée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionDetail'
        '400':
          description: Données de la transaction invalides
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Transaction non trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Supprimer une transaction
      description: Supprime une transaction spécifique.
      parameters:
        - in: path
          name: accountId
          schema:
            type: string
          description: ID du compte
          required: true
        - in: path
          name: transactionId
          schema:
            type: string
          description: ID de la transaction
          required: true
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Transaction supprimée avec succès
        '400':
          description: Requête incorrecte
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Transaction non trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          description: user email
        password:
          type: string
          description: user password
        firstName:
          type: string
          description: user first name
        lastName:
          type: string
          description: user last name
    Login:
      type: object
      properties:
        email:
          type: string
          description: user email
        password:
          type: string
          description: user password
    ApiResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        body:
          type: object
          properties:
            id:
              type: string
            email:
              type: string
    LoginResponse:
      type: object
      properties:
        token:
          type: string
    UserProfile:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
    Transaction:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        total:
          type: string
        date:
          type: string
        description:
          type: string
        amount:
          type: string
        balance:
          type: string
        notes:
          type: string
        category:
          type: string
    TransactionSummary:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        total:
          type: string
        date:
          type: string
        description:
          type: string
        amount:
          type: string
        balance:
          type: string
    TransactionSummaryDetail:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        total:
          type: string
        date:
          type: string
        description:
          type: string
        amount:
          type: string
        balance:
          type: string
        type:
         type: string
        notes:
          type: string
        category:
          type: string
    TransactionDetail:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        notes:
          type: string
        category:
          type: string
    Account:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        total:
          type: string
        description:
          type: string
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
